# Generated by Django 3.2.12 on 2022-03-12 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='subject')),
                ('descrition', models.CharField(blank=True, default='', max_length=5200, null=True, verbose_name='descrition')),
                ('priority', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='priority')),
                ('reply_content', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='reply_content')),
                ('reply_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'MainRequest',
                'verbose_name_plural': 'MainRequest',
                'ordering': ['-id'],
            },
        ),
    ]
