# Generated by Django 3.2.12 on 2022-03-12 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainrequest',
            name='reply_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replay', to=settings.AUTH_USER_MODEL, verbose_name='reply_user'),
        ),
    ]
