# Generated by Django 3.2.12 on 2022-03-26 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smart', '0002_alter_mainrequest_reply_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainrequest',
            name='is_share',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='is share'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='replay content')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('main_requests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart.mainrequest', verbose_name='main requests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='replay comments user')),
            ],
            options={
                'verbose_name': 'MainRequest',
                'verbose_name_plural': 'Comments',
                'ordering': ['-id'],
            },
        ),
    ]
